import { lazy, type ComponentType } from 'react'

/**
 * Telas carregadas sob demanda (um arquivo JS por tela): o primeiro carregamento fica leve
 * e cada módulo só é baixado quando o usuário abre a tela.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function carregar<M extends Record<K, ComponentType<any>>, K extends keyof M>(importar: () => Promise<M>, nome: K) {
  return lazy(() => importar().then((m) => ({ default: m[nome] })))
}

export const TrocarSenhaPage = carregar(() => import('@/features/auth/pages/TrocarSenhaPage'), 'TrocarSenhaPage')
export const EsqueciSenhaPage = carregar(() => import('@/features/auth/pages/EsqueciSenhaPage'), 'EsqueciSenhaPage')
export const RedefinirSenhaPage = carregar(() => import('@/features/auth/pages/RedefinirSenhaPage'), 'RedefinirSenhaPage')
export const ClienteFichaPage = carregar(() => import('@/features/clientes/pages/ClienteFichaPage'), 'ClienteFichaPage')
export const ClientesPage = carregar(() => import('@/features/clientes/pages/ClientesPage'), 'ClientesPage')
export const EmpresaPage = carregar(() => import('@/features/configuracoes/pages/EmpresaPage'), 'EmpresaPage')
export const PermissoesPage = carregar(() => import('@/features/configuracoes/pages/PermissoesPage'), 'PermissoesPage')
export const StatusPage = carregar(() => import('@/features/configuracoes/pages/StatusPage'), 'StatusPage')
export const TemplatesPage = carregar(() => import('@/features/configuracoes/pages/TemplatesPage'), 'TemplatesPage')
// Painel da plataforma e cadastro público
export const CriarContaPage = carregar(() => import('@/features/plataforma/pages/CriarContaPage'), 'CriarContaPage')
export const PlataformaLoginPage = carregar(() => import('@/features/plataforma/pages/PlataformaLoginPage'), 'PlataformaLoginPage')
export const PlataformaLayout = carregar(() => import('@/features/plataforma/components/PlataformaLayout'), 'PlataformaLayout')
export const PainelPlataformaPage = carregar(() => import('@/features/plataforma/pages/PainelPlataformaPage'), 'PainelPlataformaPage')
export const EmpresasPlataformaPage = carregar(() => import('@/features/plataforma/pages/EmpresasPlataformaPage'), 'EmpresasPlataformaPage')
export const EmpresaPlataformaPage = carregar(() => import('@/features/plataforma/pages/EmpresaPlataformaPage'), 'EmpresaPlataformaPage')
export const PlanosPlataformaPage = carregar(() => import('@/features/plataforma/pages/PlanosPlataformaPage'), 'PlanosPlataformaPage')
export const AvisosGatewayPage = carregar(() => import('@/features/plataforma/pages/AvisosGatewayPage'), 'AvisosGatewayPage')
export const MinhaAssinaturaPage = carregar(() => import('@/features/assinatura/pages/MinhaAssinaturaPage'), 'MinhaAssinaturaPage')
export const UsuariosPage = carregar(() => import('@/features/configuracoes/pages/UsuariosPage'), 'UsuariosPage')
export const FornecedorPage = carregar(() => import('@/features/fornecedores/pages/FornecedorPage'), 'FornecedorPage')
export const FornecedoresPage = carregar(() => import('@/features/fornecedores/pages/FornecedoresPage'), 'FornecedoresPage')
export const AcabamentosPage = carregar(() => import('@/features/produtos/pages/AcabamentosPage'), 'AcabamentosPage')
export const CategoriasPage = carregar(() => import('@/features/produtos/pages/CategoriasPage'), 'CategoriasPage')
export const MaquinasProcessosPage = carregar(() => import('@/features/produtos/pages/MaquinasProcessosPage'), 'MaquinasProcessosPage')
export const ProdutoPage = carregar(() => import('@/features/produtos/pages/ProdutoPage'), 'ProdutoPage')
export const ProdutosPage = carregar(() => import('@/features/produtos/pages/ProdutosPage'), 'ProdutosPage')
export const AprovarOrcamentoPage = carregar(() => import('@/features/publico/pages/AprovarOrcamentoPage'), 'AprovarOrcamentoPage')
export const OrcamentoEditorPage = carregar(() => import('@/features/orcamentos/pages/OrcamentoEditorPage'), 'OrcamentoEditorPage')
export const OrcamentosPage = carregar(() => import('@/features/orcamentos/pages/OrcamentosPage'), 'OrcamentosPage')
export const OrcamentosKanbanPage = carregar(() => import('@/features/orcamentos/pages/OrcamentosKanbanPage'), 'OrcamentosKanbanPage')
export const SolicitacoesPage = carregar(() => import('@/features/orcamentos/pages/SolicitacoesPage'), 'SolicitacoesPage')
export const EntregasPage = carregar(() => import('@/features/pedidos/pages/EntregasPage'), 'EntregasPage')
export const PedidoPage = carregar(() => import('@/features/pedidos/pages/PedidoPage'), 'PedidoPage')
export const PedidosKanbanPage = carregar(() => import('@/features/pedidos/pages/PedidosKanbanPage'), 'PedidosKanbanPage')
export const PedidosPage = carregar(() => import('@/features/pedidos/pages/PedidosPage'), 'PedidosPage')
export const FichaOpPage = carregar(() => import('@/features/producao/pages/FichaOpPage'), 'FichaOpPage')
export const OpPage = carregar(() => import('@/features/producao/pages/OpPage'), 'OpPage')
export const OpsPage = carregar(() => import('@/features/producao/pages/OpsPage'), 'OpsPage')
export const PcpPage = carregar(() => import('@/features/producao/pages/PcpPage'), 'PcpPage')
export const ProducaoKanbanPage = carregar(() => import('@/features/producao/pages/ProducaoKanbanPage'), 'ProducaoKanbanPage')
export const AprovarArtePage = carregar(() => import('@/features/publico/pages/AprovarArtePage'), 'AprovarArtePage')
export const WhatsAppPage = carregar(() => import('@/features/whatsapp/pages/WhatsAppPage'), 'WhatsAppPage')
export const EstoquePage = carregar(() => import('@/features/estoque/pages/EstoquePage'), 'EstoquePage')
export const AlertasEstoquePage = carregar(() => import('@/features/estoque/pages/EstoquePage'), 'AlertasEstoquePage')
export const EntradasPage = carregar(() => import('@/features/estoque/pages/EntradasPage'), 'EntradasPage')
export const NovaEntradaPage = carregar(() => import('@/features/estoque/pages/NovaEntradaPage'), 'NovaEntradaPage')
export const MovimentacoesPage = carregar(() => import('@/features/estoque/pages/MovimentacoesPage'), 'MovimentacoesPage')
export const ContasReceberPage = carregar(() => import('@/features/financeiro/pages/TitulosPage'), 'ContasReceberPage')
export const ContasPagarPage = carregar(() => import('@/features/financeiro/pages/TitulosPage'), 'ContasPagarPage')
export const FluxoPage = carregar(() => import('@/features/financeiro/pages/FluxoPage'), 'FluxoPage')
export const CalendarioPage = carregar(() => import('@/features/financeiro/pages/CalendarioPage'), 'CalendarioPage')
export const CadastrosFinanceirosPage = carregar(() => import('@/features/financeiro/pages/CadastrosFinanceirosPage'), 'CadastrosFinanceirosPage')
export const ComissoesPage = carregar(() => import('@/features/financeiro/pages/ComissoesPage'), 'ComissoesPage')
export const PdvPage = carregar(() => import('@/features/caixa/pages/PdvPage'), 'PdvPage')
export const RecebimentosPage = carregar(() => import('@/features/caixa/pages/RecebimentosPage'), 'RecebimentosPage')
export const MovimentosCaixaPage = carregar(() => import('@/features/caixa/pages/SessoesPage'), 'MovimentosCaixaPage')
export const SessoesPage = carregar(() => import('@/features/caixa/pages/SessoesPage'), 'SessoesPage')
export const RelatorioVendasPage = carregar(() => import('@/features/relatorios/pages/RelatorioPage'), 'RelatorioVendasPage')
export const RelatorioOrcamentosPage = carregar(() => import('@/features/relatorios/pages/RelatorioPage'), 'RelatorioOrcamentosPage')
export const RelatorioProducaoPage = carregar(() => import('@/features/relatorios/pages/RelatorioPage'), 'RelatorioProducaoPage')
export const RelatorioEstoquePage = carregar(() => import('@/features/relatorios/pages/RelatorioPage'), 'RelatorioEstoquePage')
export const RelatorioFinanceiroPage = carregar(() => import('@/features/relatorios/pages/RelatorioPage'), 'RelatorioFinanceiroPage')
export const RelatorioComissoesPage = carregar(() => import('@/features/relatorios/pages/RelatorioPage'), 'RelatorioComissoesPage')
